.gitmodules, README.md, apps/checksec_stats.py, hooks/filesystem.py, hooks/security.py, oswatcher/model.py, packer-templates/ubuntu-16.04-amd64.json
run [checksec](https://github.com/slimm609/checksec.sh) if file is `application/x-executable` or `epplication/x-sharedlibrary` mime type
=> Add checksec for ELF executables and libraries

README.md, apps/checksec_stats.py, hooks/system.py, oswatcher/capture.py, oswatcher/model.py, packer-templates/import_libvirt.py, requirements.txt, tools/capture_all.py
Add `checksec_stats.py` application
cc @nettrino
=> Checksec stats

hooks/filesystem.py
This PR improves the filesystem capture performance by x4 times.
It uses a py2neo transaction to update the database at the end of the capture.
cc @nettrino
=> filesystem: use py2neo transaction to improve performance

packer-templates/build_ubuntu_series.py, packer-templates/import_libvirt.py, packer-templates/template_domain.xml
* When building images with `build_ubuntu_series`, create a metadata JSON file
* Update the `import_libvirt.py` script to import the metadate file as well
=> Release date build

README.md
Added additional packages required in ubuntu under wsl
=> update packages to be installled in README.md

.github/workflows/capture_filesystem.yml, .github/workflows/capture_processes.yml, .github/workflows/capture_syscalls.yml, hooks/memory.py, hooks/process.py, hooks/syscall.py, oswatcher/model.py
Switch memory forensic hooks to Volatility
- `MemoryDumpHook`
- `ProcessListHook`
- `SyscallTableHook`
=> Memory hooks volatility

oswatcher/capture.py
=> logging: add module name

hooks/filesystem.py
=> filesystem: catch RuntimeError for libguestfs ls failure

hooks/filesystem.py
=> filesystem: use 2 commits to better differentiate added/removed files

hooks/filesystem.py
@milenkowski this is a draft of the filesystem filters implementation.
New values in the `hooks.json` configuration
~~~JSON
{
"name": "hooks.filesystem.FilesystemHook",
"configuration":
{
"enumerate": true,
"log_progress": true,
"log_progress_delay": 10,
"inode_checksums": false,
"filter": {
"type": "include",
"extensions": [".exe", ".EXE"]
}
}
},
~~~
This will include only the files matching the specified `extensions`.
You can also specify a list of MIME types:
~~~
"filter": {
"type": "include",
"mimes": ["application/x-dosexec"]
}
~~~
These values can be obtained using the `magic` library:
~~~
In [1]: import magic …
=> filesystem: add configurable filters

.github/workflows/capture_processes.yml, .github/workflows/capture_syscalls.yml, README.md, hooks.json, hooks/system.py, oswatcher/capture.py
@milenkowski this PR changes some of `hooks.json`'s keys:
~~~JSON
"configuration":
{
"neo4j_db": {
"enabled": true,
"delete": false,
"replace": true
},
"desktop_ready_delay": 0
},
~~~
so it's more clear that these keys are related to neo4j.
=> system: make release date optional for OperatingSystemHook

hooks/filesystem.py, oswatcher/model.py
=> filesystem: add setuid/setgid/sticky bits for Linux

oswatcher/model.py
=> model: add inode full_path as property

oswatcher/capture.py
=> capture: display duration

hooks/filesystem.py, hooks/security.py
This PR should fix the issues @milenkowski
=> Check os node

hooks/filesystem.py, hooks/security.py
* improve debug output
* only checksec the file if Linux
=> Update security windows

.github/workflows/lint.yml, requirements.txt
@milenkowski removing isort as it's not reliable
=> Remove isort

hooks/filesystem.py, requirements.txt
use ramfs to store temporary files
=> Shm tempfile

oswatcher/capture.py
catch JSON decode exception when loading hooks.json
=> capture: check json errors

hooks/filesystem.py, oswatcher/capture.py
handle keyboard interrupt and delete OS node in case
=> Keyboard interrupt
